name: integration-test
on:
  push:
    tags:
      - '*'
jobs:
  test-supported:
    strategy:
      matrix:
        pyver: ['3.10', '3.11', '3.12', '3.13']
        os: ['ubuntu-latest']  
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/dgbowl/yadg.git@${{ github.ref }} dgpost pytest
      - name: Clone integration-tests
        shell: bash
        run: |
          git clone https://github.com/dgbowl/integration-tests.git
          cd integration-tests
      - name: Run pytest
        shell: bash
        run: |
          pytest -vvx
  test-legacy:
    strategy:
      matrix:
        pyver: ['3.9']
        os: ['ubuntu-latest']  
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install yadg dgpost pytest
      - name: Clone integration-tests
        shell: bash
        run: |
          git clone https://github.com/dgbowl/integration-tests.git
          cd integration-tests
      - name: Run pytest
        shell: bash
        run: |
          pytest -vvx
