name: pull-request-commit
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        pyver: ['3.9']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - uses: ./.github/workflows/before-job
      - uses: ./.github/workflows/build-job
      - uses: actions/upload-artifact@v2
        with: 
          name: dist-${{ matrix.os }}-${{ matrix.pyver }}
          path: dist
  test:
    needs: [build]
    strategy:
      matrix:
        pyver: ['3.9']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - uses: ./.github/workflows/before-job
      - uses: actions/download-artifact@v2
        id:   wheel
        with:
          name: dist-${{ matrix.os }}-${{ matrix.pyver }}
      - run: echo ${{ steps.wheel.outputs.download-path }}
        shell: bash
      - run: pip install ${{ steps.wheel.outputs.download-path }}[testing]
        shell: bash
      - uses: ./.github/workflows/test-job
  pages:
    needs: [build]
    strategy:
      matrix:
        pyver: ['3.9']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - uses: ./.github/workflows/before-job
      - uses: actions/download-artifact@v2
        with:
          name: dist-${{ matrix.os }}-${{ matrix.pyver }}
      - run: pip install yadg*whl
        shell: bash
      - uses: ./.github/workflows/docs-job
      - uses: actions/upload-artifact@v2
        with: 
          name: public-${{ matrix.os }}-${{ matrix.pyver }}
          path: public