name: push-master
on:
    push:
        branches: ['master']
jobs:
    build:
        uses: ./.github/workflows/workflow-build.yml
        with:
            pyver: '3.9'
            os: 'ubuntu-latest'
    test:
        needs: [build]
        uses: ./.github/workflows/workflow-test.yml
        with:
            pyver: '3.9'
            os: 'ubuntu-latest'
    pages:
        needs: [build]
        uses: ./.github/workflows/workflow-pages.yml
        with:
            pyver: '3.9'
            os: ubuntu-latest
    deploy:
        needs: [pages]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v4
            with:
                python-version: '3.9'
          - uses: actions/download-artifact@v3
            with:
                name: public-ubuntu-latest-3.9
                path: public/master
          - uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                keep_files: true
